const roles = [
  'SUPERADMIN',
  'GESTOR_DE_ENERGIA',
  'TECNICO_DE_MANUTENCAO',
  'USUARIO',
  'FINANCEIRO',
  'SENSORES-MEDIDORES',
  'SISTEMA_NOTIFICACAO'
];

// Mapeamento de nível de acesso (1–7) conforme ideia.md
// 1 USUARIO LOCAL/SETOR  -> USUARIO
// 2 TECNICO DE MANUTENÇÃO -> TECNICO_DE_MANUTENCAO
// 3 GESTOR DE ENERGIA     -> GESTOR_DE_ENERGIA
// 4 FINANCEIRO            -> FINANCEIRO
// 5 SENSORES/MEDIDORES    -> SENSORES-MEDIDORES
// 6 SISTEMA DE NOTIFICAÇÕES -> SISTEMA_NOTIFICACAO
// 7 SUPERADMIN            -> SUPERADMIN
const roleLevels = {
  USUARIO: 1,
  TECNICO_DE_MANUTENCAO: 2,
  GESTOR_DE_ENERGIA: 3,
  FINANCEIRO: 4,
  'SENSORES-MEDIDORES': 5,
  SISTEMA_NOTIFICACAO: 6,
  SUPERADMIN: 7,
};

module.exports = { roles, roleLevels };